### ISSUE TITLE
Causes Evolution Artifact to not display monster items.

### ISSUE THREAD

**Issue by Fiocher** [killingwing02/RoR2JaggyFontFix#1]
Vanilla
![Snipaste_2024-09-03_21-00-22](https://github.com/user-attachments/assets/90d3d0fa-9c9c-4f20-bc46-5e37f7aa7fb7)

With mod
![Snipaste_2024-09-03_21-01-43](https://github.com/user-attachments/assets/94869934-2698-42e3-adbb-66c738aa30c9)

**Comment by killingwing02** [comment]
Fixed in [1.2.2](https://github.com/killingwing02/RoR2JaggyFontFix/releases/tag/1.2.2)
